In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle("df_cleaned.pkl")

In [3]:
df

Article                                              Title  \
1      Article 1                                              Scope   
2      Article 2                                 Supervisory powers   
3      Article 3  Application of stricter requirements by instit...   
4      Article 4                                        Definitions   
5      Article 5  Definitions specific to capital requirements f...   
6      Article 6                                 General principles   
7      Article 7  Derogation to the application of prudential re...   
8      Article 8  Derogation to the application of liquidity req...   
9      Article 9                    Individual consolidation method   
10    Article 10  Waiver for credit institutions permanently aff...   
11    Article 11                                  General treatment   
12    Article 12  Financial holding company or mixed financial h...   
13    Article 13  Application of disclosure requirements on a co...   
14    Article 14  Application of requirements of Part Five on a ...   
15    Article 15  Derogation to the application of own funds req...   
16    Article 16  Derogation to the application of the leverage ...   
17    Article 17  Supervision of investment firms waived from th...   
18    Article 18               Methods for prudential consolidation   
19    Article 19  Entities excluded from the scope of prudential...   
20    Article 20         Joint decisions on prudential requirements   
21    Article 21  Joint decisions on the level of application of...   
22    Article 22  Sub-consolidation in cases of entities in thir...   
23    Article 23                    Undertakings in third countries   
24    Article 24    Valuation of assets and off-balance sheet items   
25    Article 25                                     Tier 1 capital   
26    Article 26                         Common Equity Tier 1 items   
27    Article 27  Capital instruments of mutuals, cooperative so...   
28    Article 28                   Common Equity Tier 1 instruments   
29    Article 29  Capital instruments issued by mutuals, coopera...   
30    Article 30  Consequences of the conditions for Common Equi...   
..           ...                                                ...   
495  Article 495  Treatment of equity exposures under the IRB Ap...   
496  Article 496           Own funds requirements for covered bonds   
497  Article 497       Own funds requirements for exposures to CCPs   
498  Article 498                  Exemption for Commodities dealers   
499  Article 499                                           Leverage   
500  Article 500            Transitional provisions – Basel I floor   
501  Article 501  Capital requirements deduction for credit risk...   
502  Article 502                Cyclicality of capital requirements   
503  Article 503  Own funds requirements for exposures in the fo...   
504  Article 504  Capital instruments subscribed by public autho...   
505  Article 505                      Review of long-term financing   
506  Article 506                Credit risk – definition of default   
507  Article 507                                    Large exposures   
508  Article 508                               Level of application   
509  Article 509                             Liquidity requirements   
510  Article 510                    Net Stable Funding Requirements   
511  Article 511                                           Leverage   
512  Article 512               Exposures to transferred credit risk   
513  Article 513                              Macroprudential rules   
514  Article 514  Counterparty Credit Risk and the Original Expo...   
515  Article 515                          Monitoring and evaluation   
516  Article 516                                Long-term financing   
517  Article 517                     Definition of eligible capital   
518  Article 518  Review of capital instruments which may be wri...   
519  Article 519  Deduction of de

In [4]:
paragraphs = df['Paragraphs_cleaned'].tolist()
articles = df['Article'].tolist()
internal_references = df['References_internal_clean'].tolist()

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

#define vectorizer parameters
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=200000,
                                 min_df=0.2, stop_words='english',
                                 use_idf=True, ngram_range=(1,3))

tfidf_matrix = tfidf_vectorizer.fit_transform(paragraphs) #fit the vectorizer to paragraphs

print(tfidf_matrix.shape)

(524, 59)


In [36]:
npm_tfidf = tfidf_matrix.todense()

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
count_vectorizer_matrix = count_vectorizer.fit_transform(paragraphs)

count_vectorizer = count_vectorizer_matrix.todense()

In [68]:
count_vectorizer[523]

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [71]:
cosine_similarity(count_vectorizer[0], count_vectorizer[523])

array([[0.39328145]])

In [37]:
npm_tfidf[523]

matrix([[0.13337155, 0.        , 0.        , 0.        , 0.26614263,
         0.        , 0.1113896 , 0.        , 0.        , 0.10686643,
         0.        , 0.        , 0.        , 0.10443081, 0.        ,
         0.        , 0.        , 0.23054344, 0.        , 0.        ,
         0.        , 0.0996317 , 0.2447103 , 0.        , 0.09993561,
         0.18675124, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.47543447, 0.        ,
         0.        , 0.        , 0.        , 0.08918752, 0.22122225,
         0.09396248, 0.11099409, 0.        , 0.        , 0.        ,
         0.        , 0.32496685, 0.21889445, 0.        , 0.4274657 ,
         0.18377492, 0.        , 0.1863453 , 0.        ]])

In [72]:
import scipy
import numpy as np
import gensim
import re
import pandas as pd
from sklearn import feature_extraction
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from gensim import corpora, models

C:\Users\skamuf\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [73]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skamuf\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [74]:
lda_df = pd.read_pickle("df_cleaned.pkl")

In [75]:
lda_df.head()

Article                                              Title  \
1  Article 1                                              Scope   
2  Article 2                                 Supervisory powers   
3  Article 3  Application of stricter requirements by instit...   
4  Article 4                                        Definitions   
5  Article 5  Definitions specific to capital requirements f...   

                                          Paragraphs  \
1  This Regulation lays down uniform rules concer...   
2  For the purposes of ensuring compliance with t...   
3  This Regulation shall not prevent institutions...   
4  1.   For the purposes of this Regulation, the ...   
5  For the purposes of Part Three, Title II, the ...   

          References_internal_clean  \
1                             [460]   
2                                []   
3                                []   
4  [4, 2, 115, 25, 71, 301, 113, 1]   
5                                []   

                                  Paragraphs_cleaned  
1  This Regulation lays down uniform rules concer...  
2  For the purposes of ensuring compliance with t...  
3  This Regulation shall not prevent institutions...  
4  1.   For the purposes of this Regulation, the ...  
5  For the purposes of Part Three, Title II, the ...

In [76]:
paragraphs = lda_df['Paragraphs_cleaned'].tolist()

In [77]:
tokenizer = RegexpTokenizer(r'\w+')
p_stemmer = PorterStemmer()
texts = []

In [78]:
for i in paragraphs:
    
    # clean and tokenize document string
    raw = i.lower()
    tokens = tokenizer.tokenize(raw)

    # remove stop words from tokens
    stopped_tokens = [i for i in tokens if not i in stopwords]
    
    # stem tokens
    stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
    
    # add tokens to list
    texts.append(stemmed_tokens)

In [79]:
# turn our tokenized documents into a id <-> term dictionary
dictionary = corpora.Dictionary(texts)
# convert tokenized documents into a document-term matrix
corpus = [dictionary.doc2bow(text) for text in texts]

In [80]:
# generate LDA model
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics=100, id2word = dictionary, passes=20)

C:\Users\skamuf\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldamodel.py:775: RuntimeWarning: divide by zero encountered in log
  diff = np.log(self.expElogbeta)


In [81]:
lda_corpus = [max(prob,key=lambda y:y[1])
                for prob in ldamodel[corpus] ]
playlists = [[] for i in range(100)]
for i, x in enumerate(lda_corpus):
    playlists[x[0]].append(paragraphs[i])

In [82]:
docTopicProbMat = ldamodel.get_document_topics(corpus,minimum_probability=0)
listDocProb = list(docTopicProbMat)

In [83]:
probMatrix = np.zeros(shape=(len(df["Paragraphs"]),100))
for i,x in enumerate(listDocProb):      #each document i
    for t in x:     #each topic j
        probMatrix[i, t[0]] = t[1] 

In [84]:
matrix = pd.DataFrame(probMatrix)

In [85]:
cosine_similarity(matrix[3:4].values, matrix[2:3].values)

array([[0.00147547]])

In [6]:
def strtonumber(numbers):
    numbers = list(map(int, numbers))
    return numbers

In [7]:
df['References'] = df['References_internal_clean'].apply(strtonumber)

In [21]:
df

Article                                              Title  \
1      Article 1                                              Scope   
2      Article 2                                 Supervisory powers   
3      Article 3  Application of stricter requirements by instit...   
4      Article 4                                        Definitions   
5      Article 5  Definitions specific to capital requirements f...   
6      Article 6                                 General principles   
7      Article 7  Derogation to the application of prudential re...   
8      Article 8  Derogation to the application of liquidity req...   
9      Article 9                    Individual consolidation method   
10    Article 10  Waiver for credit institutions permanently aff...   
11    Article 11                                  General treatment   
12    Article 12  Financial holding company or mixed financial h...   
13    Article 13  Application of disclosure requirements on a co...   
14    Article 14  Application of requirements of Part Five on a ...   
15    Article 15  Derogation to the application of own funds req...   
16    Article 16  Derogation to the application of the leverage ...   
17    Article 17  Supervision of investment firms waived from th...   
18    Article 18               Methods for prudential consolidation   
19    Article 19  Entities excluded from the scope of prudential...   
20    Article 20         Joint decisions on prudential requirements   
21    Article 21  Joint decisions on the level of application of...   
22    Article 22  Sub-consolidation in cases of entities in thir...   
23    Article 23                    Undertakings in third countries   
24    Article 24    Valuation of assets and off-balance sheet items   
25    Article 25                                     Tier 1 capital   
26    Article 26                         Common Equity Tier 1 items   
27    Article 27  Capital instruments of mutuals, cooperative so...   
28    Article 28                   Common Equity Tier 1 instruments   
29    Article 29  Capital instruments issued by mutuals, coopera...   
30    Article 30  Consequences of the conditions for Common Equi...   
..           ...                                                ...   
495  Article 495  Treatment of equity exposures under the IRB Ap...   
496  Article 496           Own funds requirements for covered bonds   
497  Article 497       Own funds requirements for exposures to CCPs   
498  Article 498                  Exemption for Commodities dealers   
499  Article 499                                           Leverage   
500  Article 500            Transitional provisions – Basel I floor   
501  Article 501  Capital requirements deduction for credit risk...   
502  Article 502                Cyclicality of capital requirements   
503  Article 503  Own funds requirements for exposures in the fo...   
504  Article 504  Capital instruments subscribed by public autho...   
505  Article 505                      Review of long-term financing   
506  Article 506                Credit risk – definition of default   
507  Article 507                                    Large exposures   
508  Article 508                               Level of application   
509  Article 509                             Liquidity requirements   
510  Article 510                    Net Stable Funding Requirements   
511  Article 511                                           Leverage   
512  Article 512               Exposures to transferred credit risk   
513  Article 513                              Macroprudential rules   
514  Article 514  Counterparty Credit Risk and the Original Expo...   
515  Article 515                          Monitoring and evaluation   
516  Article 516                                Long-term financing   
517  Article 517                     Definition of eligible capital   
518  Article 518  Review of capital instruments which may be wri...   
519  Article 519  Deduction of de

In [9]:
frame = pd.DataFrame(columns = ['Article1', 'Article1_Paragraphs', 'TFIDF_vec1', 'Article2', 'Article2_Paragraphs', 'TFIDF_vec2'])
frame.index = frame.index + 1

In [10]:
frame

Empty DataFrame
Columns: [Article1, Article1_Paragraphs, TFIDF_vec1, Article2, Article2_Paragraphs, TFIDF_vec2]
Index: []

In [56]:
from sklearn.metrics.pairwise import cosine_similarity 
cosine_similarity((npm_tfidf[0]), (npm_tfidf[2]))

array([[0.39517604]])

In [88]:
articles1 = list()
paragraphs1 = list()
articles2 = list()
paragraphs2 = list()
tfidf_cosine_a = list()
count_vec_cosine_a = list()
lda_cosine_a = list()
label = list()

articles1b = list()
paragraphs1b = list()
articles2b = list()
paragraphs2b = list()
tfidf_cosine_b = list()
count_vec_cosine_b = list()
lda_cosine_b = list()
labelb = list()

for x in range (1, len(df)):
    numbers = df['References_internal_clean'][x]
    numbers = list(map(int, numbers))
    for y in range (1, len(df)):
        if y in numbers:
            articles1.append(df['Article'][x])
            paragraphs1.append(df['Paragraphs_cleaned'][x])
            articles2.append(df['Article'][y])
            paragraphs2.append(df['Paragraphs_cleaned'][y])
            tfidf_cosine_a.append(float(cosine_similarity((npm_tfidf[x-1]), (npm_tfidf[y-1]))))
            count_vec_cosine_a.append(float(cosine_similarity((count_vectorizer[x-1]), (count_vectorizer[y-1]))))
            lda_cosine_a.append(float(cosine_similarity(matrix[(x-1):x].values, matrix[(y-1):y].values)))
            label.append(1)
        else:
            articles1b.append(df['Article'][x])
            paragraphs1b.append(df['Paragraphs_cleaned'][x])
            articles2b.append(df['Article'][y])
            paragraphs2b.append(df['Paragraphs_cleaned'][y])
            tfidf_cosine_b.append(float(cosine_similarity((npm_tfidf[x-1]), (npm_tfidf[y-1]))))
            count_vec_cosine_b.append(float(cosine_similarity((count_vectorizer[x-1]), (count_vectorizer[y-1]))))
            lda_cosine_b.append(float(cosine_similarity(matrix[(x-1):x].values, matrix[(y-1):y].values)))
            labelb.append(0)  

In [99]:
crr_articles = { 'articles1': articles1,'paragraphs1': paragraphs1, 'articles2': articles2, 'paragraphs2': paragraphs2, 'tfidf_cosine': tfidf_cosine_a, 'count_vec_cosine': count_vec_cosine_a, 'lda_cosine': lda_cosine_a,'label': label}

frame = pd.DataFrame(crr_articles, columns = ['articles1', 'paragraphs1', 'articles2', 'paragraphs2', 'label',  'tfidf_cosine', 'count_vec_cosine', 'lda_cosine'])

In [100]:
crr_articles2 = { 'articles1': articles1b,'paragraphs1': paragraphs1b, 'articles2': articles2b, 'paragraphs2': paragraphs2b, 'tfidf_cosine': tfidf_cosine_b, 'count_vec_cosine': count_vec_cosine_b, 'lda_cosine': lda_cosine_b, 'label': labelb}

frame2 = pd.DataFrame(crr_articles2, columns = ['articles1', 'paragraphs1', 'articles2', 'paragraphs2', 'label', 'tfidf_cosine', 'count_vec_cosine', 'lda_cosine'])

In [91]:
len(frame2)

272339

In [92]:
len(frame)

1190

In [94]:
frame2.head()

articles1                                        paragraphs1  articles2  \
0  Article 1  This Regulation lays down uniform rules concer...  Article 1   
1  Article 1  This Regulation lays down uniform rules concer...  Article 2   
2  Article 1  This Regulation lays down uniform rules concer...  Article 3   
3  Article 1  This Regulation lays down uniform rules concer...  Article 4   
4  Article 1  This Regulation lays down uniform rules concer...  Article 5   

                                         paragraphs2  tfidf_cosine  \
0  This Regulation lays down uniform rules concer...      1.000000   
1  For the purposes of ensuring compliance with t...      0.398843   
2  This Regulation shall not prevent institutions...      0.395176   
3  1.   For the purposes of this Regulation, the ...      0.312056   
4  For the purposes of Part Three, Title II, the ...      0.017257   

   count_vec_cosine  lda_cosine  label  
0          1.000000    1.000000      0  
1          0.425165    0.001252      0  
2          0.313275    0.000898      0  
3          0.474995    0.000236      0  
4          0.272544    0.000939      0

In [95]:
#Count common words
def common_words(x):
    q1, q2 = x
    return len(set(str(q1).lower().split()) & set(str(q2).lower().split()))

In [101]:
frames = [frame, frame2]
result = pd.concat(frames)
len(result)

273529

In [102]:
result.head()

articles1                                        paragraphs1    articles2  \
0  Article 1  This Regulation lays down uniform rules concer...  Article 460   
1  Article 4  1.   For the purposes of this Regulation, the ...    Article 1   
2  Article 4  1.   For the purposes of this Regulation, the ...    Article 2   
3  Article 4  1.   For the purposes of this Regulation, the ...    Article 4   
4  Article 4  1.   For the purposes of this Regulation, the ...   Article 25   

                                         paragraphs2  label  tfidf_cosine  \
0  1.   The Commission shall be empowered to adop...      1      0.159495   
1  This Regulation lays down uniform rules concer...      1      0.312056   
2  For the purposes of ensuring compliance with t...      1      0.208647   
3  1.   For the purposes of this Regulation, the ...      1      1.000000   
4  The Tier 1 capital of an institution consists ...      1      0.309379   

   count_vec_cosine  lda_cosine  
0          0.468586    0.000427  
1          0.474995    0.000236  
2          0.490329    0.001997  
3          1.000000    1.000000  
4          0.644046    0.009585

In [103]:
result['common_words'] = result[['paragraphs1', 'paragraphs2']].apply(common_words, axis=1)

In [104]:
result.head()

articles1                                        paragraphs1    articles2  \
0  Article 1  This Regulation lays down uniform rules concer...  Article 460   
1  Article 4  1.   For the purposes of this Regulation, the ...    Article 1   
2  Article 4  1.   For the purposes of this Regulation, the ...    Article 2   
3  Article 4  1.   For the purposes of this Regulation, the ...    Article 4   
4  Article 4  1.   For the purposes of this Regulation, the ...   Article 25   

                                         paragraphs2  label  tfidf_cosine  \
0  1.   The Commission shall be empowered to adop...      1      0.159495   
1  This Regulation lays down uniform rules concer...      1      0.312056   
2  For the purposes of ensuring compliance with t...      1      0.208647   
3  1.   For the purposes of this Regulation, the ...      1      1.000000   
4  The Tier 1 capital of an institution consists ...      1      0.309379   

   count_vec_cosine  lda_cosine  common_words  
0          0.468586    0.000427            29  
1          0.474995    0.000236            57  
2          0.490329    0.001997            17  
3          1.000000    1.000000          1423  
4          0.644046    0.009585            13

In [105]:
result.to_pickle('entireDF_tfidf_lda_countvec_commonwords.pkl')